"""Add is_private with default

Revision ID: 4a698315540d
Revises: 
Create Date: 2025-06-24 20:02:32.505532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a698315540d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        op.add_column('post', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('image_file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('post', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('is_private')

    # ### end Alembic commands ###
